# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "GESTALTA - Shibari Artist, Performer, Teacher & Model"
email: gestalta22@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Gestalta is an artist and model based in Berlin & London. She specialises in shibari (kinbaku / Japanese rope bondage) as both a performance artist and teacher.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gestalta.co.uk" # the base hostname & protocol for your site
twitter_username: gestalta
github_username:  gestalta

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
